linkerdVersion: stable-2.8.0
externalIssuer: false
controlPlane:
    # namespace: l5d-conformance
    config:   
        ha: false
        flags:
            - "--controller-log-level"
            - "debug"
            - "--proxy-log-level"
            - "warn,linkerd2_proxy=debug"
testCase:
    lifecycle:
        skip: false
        reinstall: false 
        uninstall: true
        upgradeFromVersion: stable-2.7.1
    inject:
        skip: false
        clean: true
    ingress:
        skip: true
        config:
            controllers:
                - nginx
