name: KinD Conformance Tests 
on:
  pull_request: {}
  push: {}
jobs:
  kind_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: helm/kind-action@v1.0.0-rc.1
    - name: Running conformance tests in KinD cluster
      run: |
          go test -timeout 1h -ginkgo.v
